#include <obs-module.h>
#include <obs.h>

#include <cstdio>
#include <string>

#define S_SERVER "server_url"
#define S_ROOM "room"
#define S_PIN "pin"
#define S_WIDTH "width"
#define S_HEIGHT "height"
#define S_FPS "fps"
#define S_TRANSPARENT "transparent"

struct kdr_camera {
    obs_source_t *source = nullptr;
    obs_source_t *browser = nullptr;
    std::string url;
    uint32_t width = 1920;
    uint32_t height = 1080;
    int fps = 30;
};

static const char *kdr_get_name(void *)
{
    return "KDR Camera";
}

static std::string trim_server(std::string value)
{
    while (!value.empty() && value.back() == '/')
        value.pop_back();

    if (value.empty())
        value = "http://127.0.0.1:8080";

    return value;
}

static std::string make_url(const char *server, const char *room, const char *pin)
{
    std::string base = trim_server(server ? server : "");
    std::string url = base + "/?room=";

    // Room IDs generated by KDR are alphanumeric. Keep URL construction simple
    // and encode the few characters that can commonly be entered manually.
    std::string room_value = room ? room : "KDRCAM";
    for (char c : room_value) {
        if (c == ' ')
            url += "%20";
        else if (c == '#')
            url += "%23";
        else if (c == '?')
            url += "%3F";
        else if (c == '&')
            url += "%26";
        else
            url += c;
    }

    url += "&view=obs";

    if (pin && *pin) {
        url += "&pin=";
        url += pin;
    }

    return url;
}

static void release_browser(kdr_camera *data)
{
    if (!data->browser)
        return;

    obs_source_release(data->browser);
    data->browser = nullptr;
}

static void update_browser(kdr_camera *data, obs_data_t *settings)
{
    const char *server = obs_data_get_string(settings, S_SERVER);
    const char *room = obs_data_get_string(settings, S_ROOM);
    const char *pin = obs_data_get_string(settings, S_PIN);

    data->width = (uint32_t)obs_data_get_int(settings, S_WIDTH);
    data->height = (uint32_t)obs_data_get_int(settings, S_HEIGHT);
    data->fps = (int)obs_data_get_int(settings, S_FPS);

    if (data->fps < 1) data->fps = 30;
    if (data->width < 320) data->width = 1920;
    if (data->height < 180) data->height = 1080;

    data->url = make_url(server, room, pin);

    // KDR Camera uses OBS Browser Source as the WebRTC rendering engine.
    // This keeps the transport identical to the working KDR Camera web client.
    obs_data_t *browser_settings = obs_data_create();
    obs_data_set_string(browser_settings, "url", data->url.c_str());
    obs_data_set_int(browser_settings, "width", data->width);
    obs_data_set_int(browser_settings, "height", data->height);
    obs_data_set_int(browser_settings, "fps", data->fps);
    obs_data_set_bool(browser_settings, "reroute_audio", false);
    obs_data_set_bool(browser_settings, "shutdown", false);
    obs_data_set_bool(browser_settings, "restart_when_active", true);

    release_browser(data);

    data->browser = obs_source_create_private(
        "browser_source",
        "KDR Camera WebRTC",
        browser_settings
    );

    if (!data->browser) {
        blog(LOG_ERROR,
             "[KDR Camera] Could not create OBS Browser Source. "
             "Please make sure Browser Source is enabled in OBS Studio.");
    } else {
        blog(LOG_INFO, "[KDR Camera] Connected to %s", data->url.c_str());
    }

    obs_data_release(browser_settings);
}

static void *kdr_create(obs_data_t *settings, obs_source_t *source)
{
    auto *data = new kdr_camera;
    data->source = source;

    update_browser(data, settings);
    return data;
}

static void kdr_destroy(void *ptr)
{
    auto *data = static_cast<kdr_camera *>(ptr);
    if (!data)
        return;

    release_browser(data);
    delete data;
}

static void kdr_update(void *ptr, obs_data_t *settings)
{
    auto *data = static_cast<kdr_camera *>(ptr);
    if (!data)
        return;

    update_browser(data, settings);
}

static void kdr_video_render(void *ptr, gs_effect_t *)
{
    auto *data = static_cast<kdr_camera *>(ptr);

    if (data && data->browser)
        obs_source_video_render(data->browser);
}

static uint32_t kdr_width(void *ptr)
{
    auto *data = static_cast<kdr_camera *>(ptr);
    return data ? data->width : 1920;
}

static uint32_t kdr_height(void *ptr)
{
    auto *data = static_cast<kdr_camera *>(ptr);
    return data ? data->height : 1080;
}

static void kdr_defaults(obs_data_t *settings)
{
    obs_data_set_default_string(settings, S_SERVER, "http://127.0.0.1:8080");
    obs_data_set_default_string(settings, S_ROOM, "KDRCAM");
    obs_data_set_default_string(settings, S_PIN, "");
    obs_data_set_default_int(settings, S_WIDTH, 1920);
    obs_data_set_default_int(settings, S_HEIGHT, 1080);
    obs_data_set_default_int(settings, S_FPS, 30);
    obs_data_set_default_bool(settings, S_TRANSPARENT, false);
}

static obs_properties_t *kdr_properties(void *)
{
    obs_properties_t *props = obs_properties_create();

    obs_properties_add_text(
        props, S_SERVER, "KDR Server",
        OBS_TEXT_DEFAULT
    );

    obs_properties_add_text(
        props, S_ROOM, "Room / Camera ID",
        OBS_TEXT_DEFAULT
    );

    obs_properties_add_text(
        props, S_PIN, "PIN (optional)",
        OBS_TEXT_PASSWORD
    );

    obs_properties_add_int(
        props, S_WIDTH, "Width",
        320, 3840, 1
    );

    obs_properties_add_int(
        props, S_HEIGHT, "Height",
        180, 2160, 1
    );

    obs_properties_add_int(
        props, S_FPS, "FPS",
        1, 60, 1
    );

    obs_properties_add_bool(
        props, S_TRANSPARENT, "Transparent background"
    );

    return props;
}

obs_source_info kdr_camera_source_info = {
    .id = "kdr_camera",
    .type = OBS_SOURCE_TYPE_INPUT,
    .output_flags = OBS_SOURCE_VIDEO,
    .get_name = kdr_get_name,
    .create = kdr_create,
    .destroy = kdr_destroy,
    .update = kdr_update,
    .get_defaults = kdr_defaults,
    .get_properties = kdr_properties,
    .video_render = kdr_video_render,
    .get_width = kdr_width,
    .get_height = kdr_height,
    .icon_type = OBS_ICON_TYPE_CAMERA,
};
